language: scala
scala:
  - 2.11.8

cache:
directories:
  - $HOME/.m2

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: yaooqinn@hotmail.com
  name: Kent Yao
  on:
    branch: master

script:
  - mvn package -q -Dmaven.javadoc.skip=true -B -V

notifications:
  email: false
